export declare const space: number[];
export declare const fontSizes: number[];
export declare const radii: number[];
export declare const zIndexes: number[];
declare const exportedColors: {
    transparent: string;
    pearl: string;
    alertRed: string;
    warning: string;
    black: string;
    dark: string;
    separator: string;
    fog: string;
    gold: string;
    graphite: string;
    grey: string;
    identity: string;
    lightFog: string;
    sliderGrey: string;
    lightGraphite: string;
    lightGrey: string;
    starYellow: string;
    orange: string;
    positiveGreen: string;
    greenPill: string;
    smoke: string;
    wallet: string;
    blueTransparentBackground: string;
    pillActiveBackground: string;
    lightGreen: string;
    lightRed: string;
    lightWarning: string;
    white: string;
    experimentalBlue: string;
    marketUp_eastern: string;
    marketUp_western: string;
    marketDown_eastern: string;
    marketDown_western: string;
};
export { exportedColors as colors };
export declare type Theme = {
    sizes: {
        topBarHeight: number;
        sideBarWidth: number;
    };
    radii: number[];
    fontSizes: number[];
    space: number[];
    colors: Record<string, any>;
    zIndexes: number[];
};
declare const theme: Theme;
export default theme;
