require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ledgerlivemobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Pods for ledgerlivemobile
  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  pod 'djinni_objc', :path => '../node_modules/@ledgerhq/react-native-ledger-core'
  pod 'ledger-core-objc', :path => '../node_modules/@ledgerhq/react-native-ledger-core'
  pod 'RNLibLedgerCore', :path => '../node_modules/@ledgerhq/react-native-ledger-core'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  # TODO: remove this once MultiPlatformBleAdapter gets released to 0.1.9
  # https://github.com/dotintent/MultiPlatformBleAdapter/issues/79
  # https://github.com/dotintent/MultiPlatformBleAdapter/pull/80
  pod 'MultiplatformBleAdapter', :git => 'https://github.com/below/MultiPlatformBleAdapter', :tag => '0.1.9'

  target 'ledgerlivemobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
     end
  end
end
