# This is a basic workflow to help you get started with Actions

name: Detox E2E Android

on:
  workflow_dispatch: # we keep this trigger for testing purpose
    inputs:
      prNumber:
        description: pr number to trigger on
        required: true

jobs:
  echo-coucou:
    name: "Echo coucou"
    runs-on: macos-latest
    steps:
      - name: echo coucou
        run: echo "coucou"
      - name: echo $ANDROID_HOME
        run: echo $ANDROID_HOME
